// <auto-generated />
using System;
using System.Text.Json;
using Atlas.PARS.Api.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.PARS.Api.Datos.Migraciones
{
    [DbContext(typeof(ContextoAtlas))]
    partial class ContextoAtlasModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.Operacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("IdRecursoProtegido")
                        .HasColumnType("uuid")
                        .HasColumnName("id_recurso_protegido");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_operaciones");

                    b.HasIndex("IdRecursoProtegido", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_operaciones_id_recurso_protegido_codigo");

                    b.ToTable("operaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_operaciones_codigo_formato", "codigo ~ '^[A-Z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.Organizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id")
                        .HasName("pk_organizaciones");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_organizaciones_codigo");

                    b.ToTable("organizaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizaciones_codigo_formato", "codigo ~ '^[A-Z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.RecursoProtegido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("IdOrganizacion")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_recursos_protegidos");

                    b.HasIndex("IdOrganizacion", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_recursos_protegidos_id_organizacion_codigo");

                    b.ToTable("recursos_protegidos", null, t =>
                        {
                            t.HasCheckConstraint("ck_recursos_protegidos_codigo_formato", "codigo ~ '^[A-Z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.ReglaAutorizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("IdOperacion")
                        .HasColumnType("uuid")
                        .HasColumnName("id_operacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_reglas_autorizacion");

                    b.HasIndex("IdOperacion", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_reglas_autorizacion_id_operacion_codigo");

                    b.ToTable("reglas_autorizacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_reglas_autorizacion_codigo_formato", "codigo ~ '^[A-Z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.VersionRegla", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Condiciones")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("condiciones");

                    b.Property<string>("DecisionSiCumple")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("decision_si_cumple");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdReglaAutorizacion")
                        .HasColumnType("uuid")
                        .HasColumnName("id_regla_autorizacion");

                    b.Property<string>("NumeroVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numero_version");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer")
                        .HasColumnName("prioridad");

                    b.Property<DateTimeOffset>("VigenciaDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateTimeOffset?>("VigenciaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id")
                        .HasName("pk_versiones_regla");

                    b.HasIndex("IdReglaAutorizacion", "NumeroVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_versiones_regla_id_regla_autorizacion_numero_version");

                    b.HasIndex("IdReglaAutorizacion", "VigenciaDesde")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_versiones_regla_vigencia");

                    b.ToTable("versiones_regla", null, t =>
                        {
                            t.HasCheckConstraint("ck_versiones_regla_condiciones_objeto", "jsonb_typeof(condiciones) = 'object'");

                            t.HasCheckConstraint("ck_versiones_regla_decision_si_cumple_valor", "decision_si_cumple IN ('PERMIT', 'DENY', 'CHALLENGE')");

                            t.HasCheckConstraint("ck_versiones_regla_numero_version_formato", "numero_version ~ '^[0-9]+\\.[0-9]+\\.[0-9]+$'");

                            t.HasCheckConstraint("ck_versiones_regla_prioridad_no_negativa", "prioridad >= 0");

                            t.HasCheckConstraint("ck_versiones_regla_vigencia_rango", "vigencia_hasta IS NULL OR vigencia_hasta > vigencia_desde");
                        });
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.Operacion", b =>
                {
                    b.HasOne("Atlas.PARS.Api.Modelos.Entidades.RecursoProtegido", "RecursoProtegido")
                        .WithMany("Operaciones")
                        .HasForeignKey("IdRecursoProtegido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operaciones_recursos_protegidos_id_recurso_protegido");

                    b.Navigation("RecursoProtegido");
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.RecursoProtegido", b =>
                {
                    b.HasOne("Atlas.PARS.Api.Modelos.Entidades.Organizacion", "Organizacion")
                        .WithMany("RecursosProtegidos")
                        .HasForeignKey("IdOrganizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recursos_protegidos_organizaciones_id_organizacion");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.ReglaAutorizacion", b =>
                {
                    b.HasOne("Atlas.PARS.Api.Modelos.Entidades.Operacion", "Operacion")
                        .WithMany("ReglasAutorizacion")
                        .HasForeignKey("IdOperacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reglas_autorizacion_operaciones_id_operacion");

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.VersionRegla", b =>
                {
                    b.HasOne("Atlas.PARS.Api.Modelos.Entidades.ReglaAutorizacion", "ReglaAutorizacion")
                        .WithMany("VersionesRegla")
                        .HasForeignKey("IdReglaAutorizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versiones_regla_reglas_autorizacion_id_regla_autorizacion");

                    b.Navigation("ReglaAutorizacion");
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.Operacion", b =>
                {
                    b.Navigation("ReglasAutorizacion");
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.Organizacion", b =>
                {
                    b.Navigation("RecursosProtegidos");
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.RecursoProtegido", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("Atlas.PARS.Api.Modelos.Entidades.ReglaAutorizacion", b =>
                {
                    b.Navigation("VersionesRegla");
                });
#pragma warning restore 612, 618
        }
    }
}
